version: "3"
services:
  ap_staging:
    build:
      context: ./ap
    ports:
      - "8888:8000"
    command: pipenv run start
    volumes:
      - ./ap/backend:/app/backend
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings.staging"
  ss:
    image: redis:6.2.1
    ports:
      - "6379:6379"
    command: redis-server --logfile /var/log/redis/redis.log --loglevel verbose
    volumes:
      - redis-data:/data
      - ./ss/log/redis/:/var/log/redis/
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tomayto_me
    volumes:
      - postgres-db:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8889:8080"
  web:
    build:
      context: ./web
    # image: nginx:stable
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - web-data:/var/www/app
    ports:
      - "8880:80"

volumes:
  postgres-db:
    driver: local
  redis-data:
    driver: local
  web-data:
    driver: local
