# Generated by Django 3.2.2 on 2021-05-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_mod_tomayto_me_models_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="todo.project",
                verbose_name="プロジェクトタスク",
            ),
            preserve_default=False,
        ),
    ]
