# Generated by Django 3.2.2 on 2021-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_mod_tomayto_me_models_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='順番'),
        ),
    ]
