# Generated by Django 3.2 on 2021-05-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo.utils


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MstPomodoroSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_time", models.IntegerField(verbose_name="作業時間")),
                ("short_break_time", models.IntegerField(verbose_name="短い休憩時間")),
                ("long_break_time", models.IntegerField(verbose_name="長い休憩時間：時間")),
                (
                    "long_break_pomodoro",
                    models.IntegerField(verbose_name="長い休憩時間：ポモドーロ"),
                ),
            ],
            options={
                "verbose_name": "ポモドーロ設定マスタ",
                "verbose_name_plural": "ポモドーロ設定マスタ",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="プロジェクト名")),
                (
                    "status",
                    models.CharField(
                        choices=[("INCOMPLETE", "未完了"), ("COMPLETE", "完了")],
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                ("explain", models.CharField(max_length=1000, verbose_name="説明")),
                (
                    "thumbnail",
                    models.FileField(
                        upload_to=todo.utils.upload_to_info, verbose_name="サムネイル"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="締め切り")),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有ユーザ",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト",
                "verbose_name_plural": "プロジェクト",
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField(verbose_name="参加日")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todo.project",
                        verbose_name="プロジェクト",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="メンバーユーザ",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクトメンバー",
                "verbose_name_plural": "プロジェクトメンバー",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="タスク名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "TODO"),
                            ("WORKING", "作業中"),
                            ("COMPLETE", "完了"),
                        ],
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                ("start_date_time", models.DateTimeField(verbose_name="開始日時")),
                ("end_date_time", models.DateTimeField(verbose_name="終了日時")),
                ("memo", models.TextField(verbose_name="メモ")),
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク",
            },
        ),
        migrations.CreateModel(
            name="TaskPomodoro",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time_minutes", models.BigIntegerField(verbose_name="ポモドーロ時間")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todo.task",
                        verbose_name="対象タスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "タスクポモドーロ管理",
                "verbose_name_plural": "タスクポモドーロ管理",
            },
        ),
        migrations.CreateModel(
            name="TaskMemberAssign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pj_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todo.projectmember",
                        verbose_name="プロジェクトメンバー",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todo.task",
                        verbose_name="アサインタスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "タスクメンバーアサイン管理",
                "verbose_name_plural": "タスクメンバーアサイン管理",
            },
        ),
        migrations.CreateModel(
            name="MstUserPomodoroSetting",
            fields=[
                (
                    "mstpomodorosetting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todo.mstpomodorosetting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="対象ユーザ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ポモドーロユーザ設定マスタ",
                "verbose_name_plural": "ポモドーロユーザ設定マスタ",
            },
            bases=("todo.mstpomodorosetting",),
        ),
    ]
