# Generated by Django 3.2.2 on 2021-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_mod_tomayto_me_models_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='explain',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
    ]
